"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { money } from "@/lib/domain";

type Employee = { id: string; name: string; role: string };
type Overview = any;
const request = async (url: string, body?: unknown) => {
  const response = await fetch(url, body ? { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) } : undefined);
  const json = await response.json(); if (!response.ok) throw new Error(json.error ?? "Request failed."); return json;
};

export default function Home() {
  const [overview, setOverview] = useState<Overview | null>(null); const [employees, setEmployees] = useState<Employee[]>([]); const [actorId, setActorId] = useState(""); const [notice, setNotice] = useState(""); const [telegramUserId, setTelegramUserId] = useState("");
  const actor = useMemo(() => employees.find((person) => person.id === actorId), [employees, actorId]);
  const load = async (requestedActorId = actorId) => { try {
    const people = employees.length ? { employees } : await fetch("/api/employees").then((r) => r.json());
    if (people.error) throw new Error(people.error);
    const resolvedActorId = requestedActorId || people.employees[0]?.id;
    if (!resolvedActorId) throw new Error("No demonstration employees are configured.");
    const data = await fetch(`/api/overview?actorId=${encodeURIComponent(resolvedActorId)}`).then((r) => r.json());
    if (data.error) throw new Error(data.error);
    setEmployees(people.employees); setOverview(data); if (!actorId) setActorId(resolvedActorId);
  } catch (error) { setNotice(error instanceof Error ? error.message : "Could not load data."); } };
  useEffect(() => { void load(); }, []);
  useEffect(() => { if (actorId) void load(actorId); }, [actorId]);
  const syncMessage = (result: any) => `Sheets: ${result.syncStatus}.${result.syncError ? ` Error: ${result.syncError}` : ""}`;
  const submit = async (event: FormEvent<HTMLFormElement>, kind: "sale" | "expense") => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const number = (name: string) => Number(form.get(name)); const data = kind === "sale" ? { reference: form.get("reference"), customer: form.get("customer"), project: form.get("project"), description: form.get("description"), amount: number("amount"), split: { richard: number("richard"), anastasia: number("anastasia"), jeanClaude: number("jeanClaude") } } : { reference: form.get("reference"), description: form.get("description"), category: form.get("category"), amount: number("amount"), proposedAllocation: form.get("allocation") }; try { const result = await request("/api/transactions", { actorId, kind, data }); setNotice(`${result.reference} saved. Status: ${result.status}; ${syncMessage(result)}`); formElement.reset(); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "Submission failed."); } };
  const decision = async (body: object) => { try { const result = await request("/api/decisions", { actorId, ...body }); setNotice(result.unchanged ? `${result.reference} was already approved; totals were not changed.` : `${result.reference} updated. ${syncMessage(result)} Telegram: ${result.notificationStatus ?? "not required"}.`); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "Action failed."); } };
  const linkTelegram = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const employeeId = String(new FormData(event.currentTarget).get("employeeId")); try { await request("/api/manager/link-telegram", { actorId, employeeId, telegramUserId }); setNotice("Telegram user ID linked. The person must now start the bot in a private chat."); setTelegramUserId(""); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not link account."); } };
  return <main>
    <header><p className="eyebrow">Friends Included Ltd</p><h1>Wedding guests for hire finance system</h1><p>Prepared by Anastasia Leonova. Fictional demonstration system: Supabase is the source of truth; Google Sheets is a readable synchronized copy.</p></header>
    <section className="submission-links" aria-label="Submission links"><h2>Assessment links</h2><p><a href="https://t.me/wedding_finance_sync_bot" target="_blank" rel="noreferrer">Telegram bot</a><a href="https://docs.google.com/spreadsheets/d/12UKPyciiDePCAEi_-cwZB7-DpuIAUClGVyZhVMLDKbI/edit" target="_blank" rel="noreferrer">Instructor-view Google Sheet</a><a href="https://github.com/anastasia671/wedding-guests-for-hire" target="_blank" rel="noreferrer">GitHub repository</a></p></section>
    <section className="role"><label>Demonstration role <select value={actorId} onChange={(e) => setActorId(e.target.value)}>{employees.map((person) => <option key={person.id} value={person.id}>{person.name} — {person.role}</option>)}</select></label><span>Selected role: <strong>{actor?.role ?? "loading"}</strong></span></section>
    {notice && <p className="notice" role="status">{notice}</p>}
    <section className="grid forms">
      <form onSubmit={(e) => submit(e, "sale")}><h2>Submit a sale</h2><p>For Richard, Anastasia, or Jean-Claude only.</p><Field name="reference" label="Reference" placeholder="S01" /><Field name="customer" label="Customer" /><Project /><Field name="description" label="Description" /><Field name="amount" label="Amount in euros" type="number" step="0.01" /><div className="three"><Field name="richard" label="Richard %" type="number" defaultValue="0" /><Field name="anastasia" label="Anastasia %" type="number" defaultValue="0" /><Field name="jeanClaude" label="Jean-Claude %" type="number" defaultValue="0" /></div><button>Save pending sale</button></form>
      <form onSubmit={(e) => submit(e, "expense")}><h2>Submit an expense</h2><p>For Kevin only.</p><Field name="reference" label="Reference" placeholder="E01" /><Field name="description" label="Description" /><label>Category<select name="category"><option>Materials</option><option>Travel</option><option>Other</option></select></label><Field name="amount" label="Amount in euros" type="number" step="0.01" /><label>Proposed allocation<select name="allocation"><option value="A">Project A</option><option value="B">Project B</option><option value="overhead">Company overhead</option></select></label><button>Save expense</button></form>
    </section>
    {actor?.role === "manager" && <section className="manager"><h2>Manager controls — Svetlana</h2><p>Corrections are allowed before approval. Repeating an approval does not duplicate a record or change totals.</p><div className="grid"><PendingSales records={overview?.sales?.filter((sale: any) => sale.status === "pending") ?? []} decide={decision} /><PendingExpenses records={overview?.expenses?.filter((expense: any) => expense.status === "awaiting_allocation") ?? []} decide={decision} /></div><form className="link-form" onSubmit={linkTelegram}><h3>Manager setup — link Telegram user ID</h3><label>Employee<select name="employeeId">{employees.map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select></label><label>Telegram user ID<input required value={telegramUserId} onChange={(e) => setTelegramUserId(e.target.value)} inputMode="numeric" /></label><button>Link account</button></form></section>}
    {actor?.role === "manager" ? <Dashboard data={overview} onRetry={(kind: "sale" | "expense", reference: string) => decision({ action: "retry-sync", kind, reference })} onRetryNotification={(kind: "sale" | "expense", reference: string) => decision({ action: "retry-notification", kind, reference })} /> : <MySubmissions records={overview ? [...overview.sales, ...overview.expenses] : []} />}
    <section className="instructions"><h2>How to use</h2><p>Choose a demonstration role to test the role permissions. Salespeople and Kevin see only their own submissions and statuses; Svetlana sees the manager controls, all transactions, and the financial dashboard. For the actual Telegram test, link your Telegram user ID to Richard or Kevin, start the bot in a private chat, then use <code>/sale</code> or <code>/expense</code> in the format described by the bot.</p></section>
  </main>;
}

function Field({ label, ...props }: any) { return <label>{label}<input required {...props} /></label>; }
function Project() { return <label>Project<select name="project"><option value="A">Project A</option><option value="B">Project B</option></select></label>; }
function PendingSales({ records, decide }: { records: any[]; decide: (body: any) => void }) { return <article><h3>Pending sales</h3>{records.length === 0 ? <p>None.</p> : records.map((sale) => <form className="record" key={sale.reference} onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); decide({ action: "approve-sale", reference: sale.reference, split: { richard: Number(form.get("richard")), anastasia: Number(form.get("anastasia")), jeanClaude: Number(form.get("jeanClaude")) } }); }}><strong>{sale.reference} — {money(sale.amount_cents)}</strong><span>{sale.customer}; Project {sale.project}</span><div className="three"><Field name="richard" label="Richard %" type="number" defaultValue={sale.proposed_richard} /><Field name="anastasia" label="Anastasia %" type="number" defaultValue={sale.proposed_anastasia} /><Field name="jeanClaude" label="Jean-Claude %" type="number" defaultValue={sale.proposed_jean_claude} /></div><button>Approve sale</button></form>)}</article>; }
function PendingExpenses({ records, decide }: { records: any[]; decide: (body: any) => void }) { return <article><h3>Expenses awaiting allocation</h3>{records.length === 0 ? <p>None.</p> : records.map((expense) => <form className="record" key={expense.reference} onSubmit={(event) => { event.preventDefault(); decide({ action: "approve-expense", reference: expense.reference, allocation: new FormData(event.currentTarget).get("allocation") }); }}><strong>{expense.reference} — {money(expense.amount_cents)}</strong><span>{expense.description}</span><label>Final allocation<select name="allocation" defaultValue={expense.proposed_allocation}><option value="A">Project A</option><option value="B">Project B</option><option value="overhead">Company overhead</option></select></label><button>Confirm allocation</button></form>)}</article>; }
function Dashboard({ data, onRetry, onRetryNotification }: { data: Overview; onRetry: (kind: "sale" | "expense", reference: string) => void; onRetryNotification: (kind: "sale" | "expense", reference: string) => void }) { if (!data) return <p>Loading dashboard…</p>; const card = (title: string, values: any, expenseLabel = "Allocated expenses") => <article className="card"><h3>{title}</h3><p>Approved income <b>{money(values.income)}</b></p><p>Commission expense <b>{money(values.commission)}</b></p><p>{expenseLabel} <b>{money(values.expenses)}</b></p><p className="result">Result <b>{money(values.result)}</b></p></article>; return <section className="dashboard"><h2>Financial dashboard</h2><div className="grid cards">{card("Project A", data.projects.A)}{card("Project B", data.projects.B)}{card("Company", data.company, "All recorded expenses")}</div><div className="grid details"><article><h3>Company adjustments</h3><p>Company overhead: {money(data.overhead)}</p><p>Expenses awaiting allocation: {money(data.awaiting)}</p></article><article><h3>Commission earned</h3>{Object.entries(data.commissions).map(([name, value]) => <p key={name}>{name}: {money(value as number)}</p>)}</article></div><h3>Records</h3><div className="tables"><RecordTable title="Sales" records={data.sales} kind="sale" retry={onRetry} retryNotification={onRetryNotification} /><RecordTable title="Expenses" records={data.expenses} kind="expense" retry={onRetry} retryNotification={onRetryNotification} /></div></section>; }
function MySubmissions({ records }: { records: any[] }) { return <section className="dashboard"><h2>My submissions</h2><p>Only records submitted under the selected role are shown.</p><RecordTable title="My records" records={records} /></section>; }
function RecordDetails({ record }: { record: any }) {
  if ("customer" in record) {
    const proposed = `${record.proposed_richard}% / ${record.proposed_anastasia}% / ${record.proposed_jean_claude}%`;
    const approved = record.status === "approved" ? `${record.approved_richard}% / ${record.approved_anastasia}% / ${record.approved_jean_claude}%` : "Not approved";
    return <div className="record-details"><span>{record.submitter?.name ?? "Unknown salesperson"} · Project {record.project}</span><span>{record.customer}: {record.description}</span><span>Proposed split: {proposed}</span><span>Final split: {approved}</span></div>;
  }
  return <div className="record-details"><span>{record.submitter?.name ?? "Unknown reporter"} · {record.category}</span><span>{record.description}</span><span>Proposed allocation: {record.proposed_allocation}</span><span>Final allocation: {record.final_allocation ?? "Awaiting decision"}</span></div>;
}

function RecordTable({ title, records, kind, retry, retryNotification }: any) {
  return <article><h3>{title}</h3><table><thead><tr><th>Ref and details</th><th>Amount</th><th>Status</th><th>Sync</th><th>Notification</th></tr></thead><tbody>{records.map((record: any) => {
    const retryableNotification = retryNotification && (record.notification_status === "failed" || (record.notification_status === "not_required" && !(kind === "expense" && record.final_allocation === "overhead")));
    return <tr key={record.reference}><td><strong>{record.reference}</strong><RecordDetails record={record} /></td><td>{money(record.amount_cents)}</td><td>{record.status}</td><td>{record.sync_status}{retry && record.sync_status !== "synced" && <button onClick={() => retry(kind, record.reference)}>Retry sync</button>}</td><td>{record.notification_status === "not_required" ? "No Telegram recipient linked" : record.notification_status}{retryableNotification && <button onClick={() => retryNotification(kind, record.reference)}>{record.notification_status === "failed" ? "Retry notification" : "Send after linking"}</button>}</td></tr>;
  })}</tbody></table></article>;
}
